# Generated by Django 5.0.4 on 2025-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='mail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
