# Generated by Django 5.0.4 on 2025-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_app', '0002_jobvacancy_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Video Item',
                'verbose_name_plural': 'Gallery Video',
                'ordering': ['-created_at'],
            },
        ),
    ]
