# Generated by Django 5.0.4 on 2025-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_app', '0003_ytvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
